
services:
  rabbitmq-choreography:
    image: rabbitmq:4.1.0-management-alpine
    container_name: rabbitmq-choreography
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASS}
    volumes:
       - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - rabbitmq_network
    healthcheck:
      test: [ "CMD", "rabbitmq-diagnostics", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5


  order-service-choreography:
    build: ./order-service
    container_name: order-service-choreography
    ports:
      - "4001:4001"
    environment:
      RABBITMQ_USER: ${RABBITMQ_USER}
      RABBITMQ_PASS: ${RABBITMQ_PASS}
      RABBITMQ_HOST: ${RABBITMQ_HOST}
      RABBITMQ_PORT: ${RABBITMQ_PORT}
      RABBITMQ_URL: amqp://${RABBITMQ_USER}:${RABBITMQ_PASS}@${RABBITMQ_HOST}:${RABBITMQ_PORT}/
    networks:
      - rabbitmq_network
    depends_on:
      rabbitmq-choreography:
        condition: service_healthy

  inventory-service-choreography:
    build: ./inventory-service
    container_name: inventory-service-choreography
    environment:
      RABBITMQ_USER: ${RABBITMQ_USER}
      RABBITMQ_PASS: ${RABBITMQ_PASS}
      RABBITMQ_HOST: ${RABBITMQ_HOST}
      RABBITMQ_PORT: ${RABBITMQ_PORT}
      RABBITMQ_URL: amqp://${RABBITMQ_USER}:${RABBITMQ_PASS}@${RABBITMQ_HOST}:${RABBITMQ_PORT}/
    networks:
      - rabbitmq_network
    depends_on:
      rabbitmq-choreography:
        condition: service_healthy

  notification-service-choreography:
    build: ./notification-service
    container_name: notification-service-choreography
    environment:
      RABBITMQ_USER: ${RABBITMQ_USER}
      RABBITMQ_PASS: ${RABBITMQ_PASS}
      RABBITMQ_HOST: ${RABBITMQ_HOST}
      RABBITMQ_PORT: ${RABBITMQ_PORT}
      RABBITMQ_URL: amqp://${RABBITMQ_USER}:${RABBITMQ_PASS}@${RABBITMQ_HOST}:${RABBITMQ_PORT}/
    networks:
      - rabbitmq_network
    depends_on:
      rabbitmq-choreography:
        condition: service_healthy

volumes:
  rabbitmq_data:

networks:
  rabbitmq_network:
    driver: bridge
